server:
  port: 9090

spring:
  application:
    name: GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**

            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

