server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: Admin@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

management:
  endpoints:
    web:
      exposure:
        include: health        
